name: Terraform Lint Workflow

on:
  push:
    branches:
      - feature/tflint

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Init TFLint
        run: tflint --init -c .tflint.hcl

      - name: Run TFLint
        run: tflint -c .tflint.hcl