name: TFLint

on:
  push:
    branches:
      - feature/tflint

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのクローン
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Init TFLint
        run: tflint --init -c .tflint.hcl

      - name: Run TFLint
        run: tflint -c .tflint.hcl